spring:
  profiles:
    active:
    -dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-ming-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-ming-test
